---
version: 2
jobs:
  build:
    docker:
    - image: suzukishunsuke/go-ci:0.5.1
    working_directory: /go/src/github.com/suzuki-shunsuke/go-ptr
    steps:
    - checkout
    - run: npm i
    - run: bash scripts/commitlint-circleci.sh
    - run: npm run lint
    - run: bash scripts/codecov-test.sh
    - run: test "$LOCAL" == "true" || bash <(curl -s https://codecov.io/bash)
